# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in pcs1.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "rest_cli", path: "/Users/roberto/.local/share/gems-source/rjayroach/rest_cli"
gem "flat_record", path: "/Users/roberto/.local/share/gems-source/rjayroach/flat_record"
