# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in pcs.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

# Local, unpublished (linked by local-gems)
gem "flat_record", path: File.expand_path("~/.local/share/gems/flat_record")
gem "termino", path: File.expand_path("~/.local/share/gems/termino")
