# frozen_string_literal: true

require "fileutils"

module Pcs
  module Operations
    class Reconcile < Termino::Operation
      # Writing generated files only when they change, and removing the ones
      # pcs wrote for hosts that are gone.
      module Files
        HEADER = "Generated by pcs"

        private

        # Writes content if it differs from what's there; true if it did (or
        # would, in a dry run).
        def write(path, content)
          return false if File.exist?(path) && File.read(path) == content

          step("write #{path}") do
            FileUtils.mkdir_p(File.dirname(path))
            File.write("#{path}.part", content)
            File.rename("#{path}.part", path)
          end
          true
        end

        # Files pcs wrote for hosts that are gone (or no longer configured).
        # Files pcs didn't write are left alone.
        def remove_stale(targets)
          keep = targets.flat_map { |t| host_files(t) }
          (generated_files - keep).each { |path| step("remove #{path}") { File.delete(path) } }
        end

        def host_files(target)
          [menu_path(target), asset_path(target.preseed_file), asset_path(target.post_install_file)]
        end

        def generated_files
          (Dir[File.join(@settings.netboot.menus_dir, "MAC-*.ipxe")] +
            Dir[File.join(@settings.netboot.assets_dir, "pcs", "*")]).select { |path| generated_by_pcs?(path) }
        end

        def generated_by_pcs?(path)
          File.foreach(path).first(2).any? { |line| line.include?(HEADER) }
        end
      end
    end
  end
end
